export const FUNDRAISER_UPDATE = 'FUNDRAISER_UPDATE';
export const BALANCE_RESULT = 'BALANCE';
export const BALANCE_REQUEST = 'BALANCE_REQUEST';
export const BALANCE_SUCCESS = 'BALANCE_SUCCESS';
export const BALANCE_ERROR = 'BALANCE_ERROR';
export const NEW_PURCHASE = 'NEW_PURCHASE';
